name: run

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  run-step:
    name: Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build dockerfile
        run: docker build --file Dockerfile --tag i64 .
      - name: Run dockerfile
        run: docker run i64
